### ISSUE TITLE
type in Gaussian mapping / addressing the notation

### ISSUE THREAD

**Issue by arashgmn** [tsilifis/bayesian_adaptation_VIGeodMC#1]
The second component of the mapping should be inverted based on [wiki's table](https://en.wikipedia.org/wiki/Exponential_family) on the exponential family. Also, the fact that the inverse variance is the second component itself better to be addressed to avoid confusion with such tables.

https://github.com/tsilifis/bayesian_adaptation_VIGeodMC/blob/6e83d14f40120e0d2b0006746f492b3b744affc3/stiefel_sampling/_mean_field_VI.py#L34

**Comment by tsilifis** [comment]
This maps the natural parameters of a Gaussian distribution to its mean and inverse variance (NOT variance). For the purposes for this Variational Inference algorithm is it more useful to work the inverse variance as this is the hyperparameter that has been modeled as a Gamma distribution, so the code will be kept as is. 
Panos
