### ISSUE TITLE
eta is given instead of omega

### ISSUE THREAD

**Issue by arashgmn** [tsilifis/bayesian_adaptation_VIGeodMC#2]
In this line, `z_c_mean` is receiving the natural parameter `eta` instead of the distribution parameters `omega`. This argument is mapped again to eta inside `z_c_mean` which shouldn't happen. 

https://github.com/tsilifis/bayesian_adaptation_VIGeodMC/blob/6e83d14f40120e0d2b0006746f492b3b744affc3/stiefel_sampling/_mean_field_VI.py#L152

**Comment by tsilifis** [comment]
Thanks for spotting this! 
It's now fixed by removing the map_to_eta step in z_c_mean(). 
p.
